version: '3.4'

services:

  portainer:
    image: portainer/portainer-ce

  leadmanager.db:
    image: mcr.microsoft.com/mssql/server

  leadmanager.blob:
    image: mcr.microsoft.com/azure-storage/azurite

  leadmanager.caching:
    image: redis:7.0.12-alpine

  leadmanager.messagebus:
    image: rabbitmq:3-management

  iamserver.db:
    image: mongo:6.0

  iamserver:
    container_name: iamserver
    image: ${DOCKER_REGISTRY-}iamserver
    build:
      context: .
      dockerfile: src/hosts/IAMServer/Dockerfile

  leadmanager.client:
    image: cristianomartinsdiasspbr1982/leadmanagerweb:v1.0.3
    
  leadmanager.api:
    container_name: leadmanagerapi
    image: ${DOCKER_REGISTRY-}leadmanagerapi
    build:
      context: .
      dockerfile: src/hosts/LeadManagerApi/Dockerfile

volumes:
  db_data:
  iam_db_data:
  messagebus_data:
  blob_data:
  caching_data:
  portainer_data: