services:

  portainer:
    image: portainer/portainer-ce

  leadmanager.logging-ingestion:
    image: datalust/seq:2023.4

  leadmanager.db:
    image: mcr.microsoft.com/mssql/server:latest

  iamserver.db:
    image: mongo:6.0

  leadmanager.blob:
    image: mcr.microsoft.com/azure-storage/azurite

  leadmanager.caching:
    image: redis:7.0.12-alpine

  leadmanager.messagebus:
    image: rabbitmq:3-management

  iamserver:
    image: cristianomartinsdiasspbr1982/iamserver:v1.0.0

  leadmanager.web:
    image: cristianomartinsdiasspbr1982/leadmanagerweb:v1.0.4
    
  leadmanager.api:
    image: cristianomartinsdiasspbr1982/leadmanagerapi:v1.0.10

volumes:
  db_data:
  messagebus_data:
  blob_data:
  caching_data:
  portainer_data:
  seq_data:
  iamdb_data: