apiVersion: apps/v1
kind: Deployment
metadata:
  name:  leadmanager-api
  namespace: leadmanager
  labels:
    app: leadmanager-api
spec:
  selector:
    matchLabels:
      app: leadmanager-api
  replicas: 2 # (Aqui controla-se a quantidade de instâncias desejadas no cluster)
  template:
    metadata:
      labels:
        app: leadmanager-api
    spec:
      containers:
      - name: leadmanager-api
        image: cristianomartinsdiasspbr1982/leadmanagerapi:v1.0.10 # (Importante: a imagem deve estar como pública no hub.docker.com!)
        #imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development # (Se não for preciso acessar o Swagger, coloque Production ao invés de Development)
          - name: ASPNETCORE_HTTP_PORTS # (O nro da porta deve estar igual em: containerPort do deployment + var. de ambiente ASPNETCORE_HTTP_PORTS do deployment + ports:port do service + EXPOSE PORT do dockerfile)
            value: "8080" 
          - name: DataSourceSettings__ConnectionString
            value: Data source=leadmanager-db;Initial Catalog=LeadManager;User Id=sa;Password=Y0urStr0nGP@sswoRD_2023;MultipleActiveResultSets=true;Connect timeout=30;TrustServerCertificate=True
          - name: RabbitMqConnectionSettings__HostName
            value: leadmanager-bus
        # - name: DataSourceSettings__ConnectionString
        #   valueFrom:
        #     configMapKeyRef:
        #       name: leadmanagerapi-secret
        #       key: DatabaseConnectionString
        ports:
        - containerPort: 8080 # (O nro da porta deve estar igual em: containerPort do deployment + var. de ambiente ASPNETCORE_HTTP_PORTS do deployment + ports:port do service + EXPOSE PORT do dockerfile)
      #restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: leadmanager-api-service
  namespace: leadmanager
spec:
  selector:
    app: leadmanager-api
  ports:
    - protocol: TCP
      port: 8080 # (O nro da porta deve estar igual em: containerPort do deployment + var. de ambiente ASPNETCORE_HTTP_PORTS do deployment + ports:port do service + EXPOSE PORT do dockerfile)
      targetPort: 80
  type: NodePort